CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS companies_address (
id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
state VARCHAR(255) NOT NULL,
city VARCHAR(255) NOT NULL,
street VARCHAR(255) NOT NULL,
number INTEGER NOT NULL,
postal_code VARCHAR(9) NOT NULL,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS companies (
id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
company_address_id UUID REFERENCES companies_address(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
name VARCHAR(255) NOT NULL,
cnpj VARCHAR(18) NOT NULL,
phone_number VARCHAR(16) NOT NULL,
link_client VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
company_id UUID REFERENCES companies(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS staffs (
id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
company_id UUID REFERENCES companies(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
name VARCHAR(255) NOT NULL,
surname VARCHAR(255) NOT NULL,
cpf VARCHAR(14) NOT NULL UNIQUE,
email VARCHAR(255) NOT NULL UNIQUE,
phone_number VARCHAR(16) NOT NULL,
birthdate DATE NOT NULL,
postal_code VARCHAR(9) NOT NULL,
status BOOLEAN NOT NULL,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS services (
id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
company_id UUID REFERENCES companies(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
name VARCHAR(255) NOT NULL,
description TEXT NOT NULL,
price DECIMAL(10, 2) NOT NULL,
average_duration INTEGER NOT NULL,
status BOOLEAN NOT NULL,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS schedules (
id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
week_day VARCHAR(255) NOT NULL,
start_time_1 TIME NOT NULL,
end_time_1 TIME NOT NULL,
status_1 BOOLEAN NOT NULL,
start_time_2 TIME NOT NULL,
end_time_2 TIME NOT NULL,
status_2 BOOLEAN NOT NULL,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS clients (
id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
phone_number VARCHAR(16) NOT NULL,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS appointments (
id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
client_id UUID REFERENCES clients(id) ON UPDATE CASCADE ON DELETE CASCADE,
staff_id UUID REFERENCES staffs(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
service_id UUID REFERENCES services(id) ON UPDATE CASCADE ON DELETE CASCADE,
date_hour_begin TIMESTAMP NOT NULL,
date_hour_end TIMESTAMP NOT NULL,
status VARCHAR(255) NOT NULL,
observation TEXT NOT NULL,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS services_staffs (
id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
service_id UUID REFERENCES services(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
staff_id UUID REFERENCES staffs(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS schedules_staffs (
id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
schedule_id UUID REFERENCES schedules(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
staff_id UUID REFERENCES staffs(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
);